// <auto-generated />
using MemorizeWordsAPI.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MemorizeWordsAPI.Migrations
{
    [DbContext(typeof(MWContext))]
    partial class MWContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MemorizeWordsAPI.Services.LearningSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DaysHaveLearned");

                    b.Property<int>("NumberOfDay");

                    b.Property<int>("WordListID");

                    b.Property<int>("WordNumberPerDay");

                    b.HasKey("ScheduleID");

                    b.HasIndex("WordListID");

                    b.ToTable("LearningSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleID = 1,
                            DaysHaveLearned = 2,
                            NumberOfDay = 5,
                            WordListID = 1,
                            WordNumberPerDay = 20
                        });
                });

            modelBuilder.Entity("MemorizeWordsAPI.Services.Word", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChineseMeaning");

                    b.Property<string>("EnglishWord");

                    b.Property<string>("PhoneticSymbols");

                    b.Property<int>("WordListID");

                    b.Property<string>("WordStatus");

                    b.HasKey("WordID");

                    b.HasIndex("WordListID");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("MemorizeWordsAPI.Services.WordList", b =>
                {
                    b.Property<int>("WordListID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("WordListName");

                    b.Property<int>("WordNumber");

                    b.HasKey("WordListID");

                    b.ToTable("WordLists");

                    b.HasData(
                        new
                        {
                            WordListID = 1,
                            WordListName = "A small word list for test",
                            WordNumber = 100
                        });
                });

            modelBuilder.Entity("MemorizeWordsAPI.Services.LearningSchedule", b =>
                {
                    b.HasOne("MemorizeWordsAPI.Services.WordList", "WordListIDNavigation")
                        .WithMany()
                        .HasForeignKey("WordListID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MemorizeWordsAPI.Services.Word", b =>
                {
                    b.HasOne("MemorizeWordsAPI.Services.WordList", "WordListIDNavigation")
                        .WithMany()
                        .HasForeignKey("WordListID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
